### ISSUE TITLE
Skrivefeil i datajegeren-skjema

### ISSUE THREAD

**Issue by valosnah** [datadeling/datafabrikken-portal-nextjs#30]
![image](https://user-images.githubusercontent.com/8625716/177748331-4eaa0f43-797d-4742-bfd5-3c3b4999991b.png)

**Comment by jeffreiffers** [comment]
https://github.com/datadeling/datafabrikken-portal-nextjs/pull/29/commits/c755c7ebded3b77b90cb82e406d245fa7247e143
