### ISSUE TITLE
Feil med knappene på hovedsiden

### ISSUE THREAD

**Issue by valosnah** [datadeling/datafabrikken-portal-nextjs#33]
Gjelder sidene /datalandsbyen , /juridisk-veileder-for-datadeling og /finn-data, hvis man navigerer via knappene på hovedsiden.

![image](https://user-images.githubusercontent.com/8625716/181024931-5d34fe55-9968-4b58-b58d-34c1ec789f1e.png)

Feilmeldingen foreslår å ha konsollen oppe for å se hva som kræsjer, men der ser alt fint ut.
Sidene fungerer hvis man refresher fra den svarte skjermen, men hvis du prøver å navigere tilbake fra dem, får du 404.
Navigerer man dit via toppmenyen, fungerer alt fint (inkludert når man navigerer tilbake til hovedsiden)
Ser også ut som direktelinker virker fint
Regner med det er noe portal/portal-nextjs krøll

**Comment by jeffreiffers** [comment]
Denne kan vel lukkes?

**Comment by valosnah** [comment]
Løst av https://github.com/datadeling/datafabrikken-portal-nextjs/pull/34
